add_newline = false
# start with bell character
format = """
\u0007\
$status\
$username\
$hostname\
$time\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$os\
$container\
$shell\
$character\
"""

[username]
show_always = true
format = "[$user]($style)"

[hostname]
ssh_only = false
format = "@[$hostname]($style): "

[time]
disabled = false
use_12hr = true
format = "[$time]($style): "

[status]
disabled = false
format = "[$symbol $status\n]($style)"
map_symbol = true

[cmd_duration]
show_milliseconds = true

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[c]
detect_extensions = ['c', 'h', 'cpp', 'hpp']

[aws]
disabled = true

[ruby]
# I only seem to set RUBY_VERSION, so take that out of this list
detect_variables = ["RBENV_VERSION"]

[python]
python_binary = ["python3", "python", "python2"]

[gcloud]
disabled = true
