call plug#begin('~/.vim/bundle')

Plug 'vim-scripts/AnsiEsc.vim'
Plug 'w0rp/ale'
Plug 'kien/ctrlp.vim'
Plug 'mhinz/vim-signify'
" ./deploy.py && cd ~/.vim/bundle/YouCompleteMe &&
" ./install.py --clang-completer
"Plug 'Valloric/YouCompleteMe'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'Yggdroot/indentLine'

call plug#end()

set number
set relativenumber
set showcmd
set splitright
set splitbelow
set hlsearch
set encoding=utf-8
set laststatus=2
set statusline=%f%(\ [%Y%M]%)%=%-14.(%l,%c%V%)\ %P
set tabstop=4
set shiftwidth=4

" toggle relativenumber
nnoremap <leader>r :set relativenumber!<CR>

" easier ex input
nnoremap ; :

" split navigation
nnoremap <C-h> <C-w><C-h>
nnoremap <C-j> <C-w><C-j>
nnoremap <C-k> <C-w><C-k>
nnoremap <C-l> <C-w><C-l>

" search and delete trailing whitespace
nnoremap <leader>w /\s\+$<CR>
nnoremap <leader>dw :%s/\s\+$//e<CR>

" ZA = :qa! like ZZ = :wq and ZQ = :q!
nnoremap ZA :qa!<CR>

" Backup for :CtrlPBuffer
nnoremap <leader>b :ls<CR>:b<space>
